# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number1', models.IntegerField()),
                ('contact_number2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PartnersDetails',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('select', 'SELECT'), ('B', 'Banglore'), ('H', 'Hyderabad')], default='select', max_length=20)),
                ('city', models.CharField(choices=[('select', 'SELECT'), ('B', 'Banglore'), ('H', 'Hyderabad')], default='select', max_length=20)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='wname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.PartnersDetails'),
        ),
    ]
