# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersdetails',
            name='type',
            field=models.CharField(choices=[('select', 'SELECT'), ('W', 'WORKSHOP'), ('M', 'MECHANIC')], default='select', max_length=20),
        ),
    ]
