# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20170805_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='contact_number1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='contact_number2',
            field=models.CharField(max_length=15),
        ),
    ]
