# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20170805_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='wname',
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='wname',
            field=models.ManyToManyField(to='partners.PartnersDetails'),
        ),
    ]
