# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20170805_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='wname',
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='wname',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='partners.PartnersDetails'),
            preserve_default=False,
        ),
    ]
