# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20170805_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='wname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partners.PartnersDetails'),
        ),
    ]
